import type { CompassZoneKey } from "@/types/patient";
import type { ThreeZoneRuntime } from "@/types/prediction";

/** COMPASS PI sheet zone → 3D mesh zone id */
export const COMPASS_TO_3D: Record<string, string> = {
  "4a": "A-RB",
  "1a": "A-LB",
  "5a": "A-RM",
  "2a": "A-LM",
  "6a": "A-RA",
  "3a": "A-LA",
  "7p": "P-RB-L",
  "6p": "P-RB-M",
  "1p": "P-LB-M",
  "2p": "P-LB-L",
  "9p": "P-RM-L",
  "8p": "P-RM-M",
  "3p": "P-LM-M",
  "4p": "P-LM-L",
  "10p": "A-RA",
  "5p": "A-LA",
};

export const ZONE_ANATOMY: Record<
  string,
  { side: "L" | "R"; zone: string }
> = {
  "P-LB-L": { side: "L", zone: "posterolateral" },
  "P-LM-L": { side: "L", zone: "posterolateral" },
  "P-RB-L": { side: "R", zone: "posterolateral" },
  "P-RM-L": { side: "R", zone: "posterolateral" },
  "P-LB-M": { side: "L", zone: "base" },
  "P-LM-M": { side: "L", zone: "base" },
  "P-RB-M": { side: "R", zone: "base" },
  "P-RM-M": { side: "R", zone: "base" },
  "A-LB": { side: "L", zone: "bladder_neck" },
  "A-RB": { side: "R", zone: "bladder_neck" },
  "A-LM": { side: "L", zone: "anterior" },
  "A-RM": { side: "R", zone: "anterior" },
  "A-LA": { side: "L", zone: "apex" },
  "A-RA": { side: "R", zone: "apex" },
};

export const NS_THRESHOLDS = {
  posterolateral: { grade2: 0.1, grade3: 0.3 },
  base: { grade2: 0.1, grade3: 0.35 },
} as const;

export function createDefaultZones(): Record<
  CompassZoneKey,
  import("@/types/patient").ZoneData
> {
  const keys: CompassZoneKey[] = [
    "1a",
    "2a",
    "3a",
    "4a",
    "5a",
    "6a",
    "1p",
    "2p",
    "3p",
    "4p",
    "5p",
    "6p",
    "7p",
    "8p",
    "9p",
    "10p",
    "SV-L",
    "SV-R",
  ];
  const z: Record<string, import("@/types/patient").ZoneData> = {};
  for (const k of keys) {
    z[k] = {
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      hasData: false,
      sources: {
        mri: null,
        mus: null,
        suv: null,
        biopsy_gg: null,
        core_pct: null,
        linear_mm: null,
        pct_4_5: null,
        cribriform: null,
      },
    };
  }
  return z as Record<CompassZoneKey, import("@/types/patient").ZoneData>;
}

export function createBaseThreeZones(): ThreeZoneRuntime[] {
  return [
    {
      id: "A-RB",
      name: "R Anterior Base",
      side: "R",
      level: "Base",
      region: "Anterior",
      subregion: "full",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "A-LB",
      name: "L Anterior Base",
      side: "L",
      level: "Base",
      region: "Anterior",
      subregion: "full",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "P-RB-L",
      name: "R Post Base Lat",
      side: "R",
      level: "Base",
      region: "Posterior",
      subregion: "lateral",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "P-RB-M",
      name: "R Post Base Med",
      side: "R",
      level: "Base",
      region: "Posterior",
      subregion: "medial",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "P-LB-M",
      name: "L Post Base Med",
      side: "L",
      level: "Base",
      region: "Posterior",
      subregion: "medial",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "P-LB-L",
      name: "L Post Base Lat",
      side: "L",
      level: "Base",
      region: "Posterior",
      subregion: "lateral",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "A-RM",
      name: "R Midgland Anterior",
      side: "R",
      level: "Mid",
      region: "Anterior",
      subregion: "full",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "A-LM",
      name: "L Midgland Anterior",
      side: "L",
      level: "Mid",
      region: "Anterior",
      subregion: "full",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "P-RM-L",
      name: "R Post Mid Lat",
      side: "R",
      level: "Mid",
      region: "Posterior",
      subregion: "lateral",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "P-RM-M",
      name: "R Post Mid Med",
      side: "R",
      level: "Mid",
      region: "Posterior",
      subregion: "medial",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "P-LM-M",
      name: "L Post Mid Med",
      side: "L",
      level: "Mid",
      region: "Posterior",
      subregion: "medial",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "P-LM-L",
      name: "L Post Mid Lat",
      side: "L",
      level: "Mid",
      region: "Posterior",
      subregion: "lateral",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "A-RA",
      name: "R Apex",
      side: "R",
      level: "Apex",
      region: "Anterior",
      subregion: "full",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
    {
      id: "A-LA",
      name: "L Apex",
      side: "L",
      level: "Apex",
      region: "Anterior",
      subregion: "full",
      cancer: 0.02,
      ece: 0.01,
      svi: 0.01,
      psm: 0.05,
    },
  ];
}
